wandb_version: 1

weights:
  desc: null
  value: ''
cfg:
  desc: null
  value: models/detect/yolov9.yaml
data:
  desc: null
  value: data/data.yaml
hyp:
  desc: null
  value:
    lr0: 0.01
    lrf: 0.01
    momentum: 0.937
    weight_decay: 0.0005
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    warmup_bias_lr: 0.1
    box: 7.5
    cls: 0.5
    cls_pw: 1.0
    obj: 0.7
    obj_pw: 1.0
    dfl: 1.5
    iou_t: 0.2
    anchor_t: 5.0
    fl_gamma: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    degrees: 0.0
    translate: 0.1
    scale: 0.9
    shear: 0.0
    perspective: 0.0
    flipud: 0.0
    fliplr: 0.5
    mosaic: 1.0
    mixup: 0.15
    copy_paste: 0.3
epochs:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 16
imgsz:
  desc: null
  value: 640
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
nosave:
  desc: null
  value: false
noval:
  desc: null
  value: false
noautoanchor:
  desc: null
  value: false
noplots:
  desc: null
  value: false
evolve:
  desc: null
  value: null
bucket:
  desc: null
  value: ''
cache:
  desc: null
  value: null
image_weights:
  desc: null
  value: false
device:
  desc: null
  value: '0'
multi_scale:
  desc: null
  value: false
single_cls:
  desc: null
  value: false
optimizer:
  desc: null
  value: SGD
sync_bn:
  desc: null
  value: false
workers:
  desc: null
  value: 8
project:
  desc: null
  value: runs/train
name:
  desc: null
  value: exp
exist_ok:
  desc: null
  value: false
quad:
  desc: null
  value: false
cos_lr:
  desc: null
  value: false
flat_cos_lr:
  desc: null
  value: false
fixed_lr:
  desc: null
  value: false
label_smoothing:
  desc: null
  value: 0.0
patience:
  desc: null
  value: 100
freeze:
  desc: null
  value:
  - 0
save_period:
  desc: null
  value: -1
seed:
  desc: null
  value: 0
local_rank:
  desc: null
  value: -1
min_items:
  desc: null
  value: 0
close_mosaic:
  desc: null
  value: 0
entity:
  desc: null
  value: null
upload_dataset:
  desc: null
  value: false
bbox_interval:
  desc: null
  value: -1
artifact_alias:
  desc: null
  value: latest
save_dir:
  desc: null
  value: runs/train/exp2
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709866854.663363
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 80
      3:
      - 16
      - 23
      4: 3.11.5
      5: 0.16.2
      6: 4.32.1
      8:
      - 5
      13: linux-x86_64
data_dict:
  desc: null
  value:
    train: /mnt/d/Aquarium Combined.v2-raw-1024.yolov7pytorch/train/images
    val: /mnt/d/Aquarium Combined.v2-raw-1024.yolov7pytorch/valid/images
    nc: 7
    names:
      '0': fish
      '1': jellyfish
      '2': penguin
      '3': puffin
      '4': shark
      '5': starfish
      '6': stingray
    path: /home/shawn/projects/yolov9
